read.data <- read.csv("/Users/sheesh/Downloads/Employee.csv")
print(read.data)
print(ncol(read.data))
print(nrow(read.data))
range.year <- range(read.data$JoiningYear)
print(range.year)
max.year <- subset(read.data, JoiningYear == max(JoiningYear))
print(max.year)
city.per <- subset(read.data, City == 'Bangalore')
print(city.per)
