mydata = data.frame(Q1 = sample(1:6, 100, replace = TRUE),Q2 = sample(1:6, 100, replace = TRUE),
                    Q3 = sample(1:6, 100, replace = TRUE), Q4 = sample(1:6, 100, replace = TRUE),
                    Age = sample(1:3, 100, replace = TRUE))
summary(mydata)
summary( mydata[3])
summary( mydata$Q1)
names(mydata)
nrow(mydata)
ncol(mydata)
str(mydata)
head(mydata)
head(mydata, n=5)
head(mydata, n=-1)
tail(mydata)
tail(mydata, n=5)
tail(mydata, n=-1)

library(dplyr)
sample_n(mydata, 5)
library(dplyr)
sample_frac(mydata, 0.1)
colSums(is.na(mydata))
sapply(mydata, function(y) sum(is.na(y)))
sum(is.na(mydata$Q1))